### ISSUE TITLE
03 Automation

### ISSUE THREAD

**Issue by Siole** [MagnusHJensen/simple-fortune-cookie#1]
Testing the workflow with a continuous integration pipeline

This is only done on PR level not on main branch. (Run test for both frontend and backend, and can be run in parallel.)
If this check succeeds, then the PR can be auto merged

_Optional: enforce branch protection rules, by not allowing to push directly to main, without a PR and passing checks_

**Comment by MagnusHJensen** [comment]
Even though the backend does not have any test, we still run go test in that folder, due to having more trust in our integration, if at some point tests are ever added.
